// Bio page templates - layout, colors, fonts, button styles
export const BIO_TEMPLATES = {
  classic: {
    id: 'classic',
    name: 'Classic',
    description: 'Clean white, centered layout',
    thumbnail: '/api/placeholder/classic',
    page_settings: {
      background_type: 'solid',
      background_value: '#ffffff',
      background_value_2: '#ffffff',
      text_color: '#111827',
      accent_color: '#3361FF',
      font_family: 'Inter',
      button_style: 'rounded',
      show_avatar: true,
      show_social_icons: true,
      avatar_size: 'medium',
      layout: 'centered',
    },
  },
  creator_dark: {
    id: 'creator_dark',
    name: 'Creator Dark',
    description: 'Dark background, bold headings',
    page_settings: {
      background_type: 'solid',
      background_value: '#0f172a',
      background_value_2: '#0f172a',
      text_color: '#f8fafc',
      accent_color: '#818cf8',
      font_family: 'Inter',
      button_style: 'pill',
      show_avatar: true,
      show_social_icons: true,
      avatar_size: 'medium',
      layout: 'centered',
      heading_style: 'bold',
    },
  },
  gradient_glow: {
    id: 'gradient_glow',
    name: 'Gradient Glow',
    description: 'Purple-to-blue gradient, glowing',
    page_settings: {
      background_type: 'gradient',
      background_value: '#7c3aed',
      background_value_2: '#2563eb',
      text_color: '#ffffff',
      accent_color: '#ffffff',
      font_family: 'Inter',
      button_style: 'rounded',
      show_avatar: true,
      show_social_icons: true,
      avatar_size: 'medium',
      layout: 'centered',
      button_glow: true,
    },
  },
  minimal: {
    id: 'minimal',
    name: 'Minimal',
    description: 'Off-white, thin borders',
    page_settings: {
      background_type: 'solid',
      background_value: '#fafafa',
      background_value_2: '#fafafa',
      text_color: '#374151',
      accent_color: '#6b7280',
      font_family: 'Inter',
      button_style: 'square_outline',
      show_avatar: true,
      show_social_icons: true,
      avatar_size: 'medium',
      layout: 'centered',
      border_style: 'thin',
    },
  },
  bold: {
    id: 'bold',
    name: 'Bold',
    description: 'Bright accent, large avatar',
    page_settings: {
      background_type: 'solid',
      background_value: '#ffffff',
      background_value_2: '#ffffff',
      text_color: '#111827',
      accent_color: '#ef4444',
      font_family: 'Bebas Neue',
      button_style: 'filled',
      show_avatar: true,
      show_social_icons: true,
      avatar_size: 'large',
      layout: 'centered',
      heading_style: 'uppercase',
    },
  },
  neon: {
    id: 'neon',
    name: 'Neon',
    description: 'Black, neon green accents',
    page_settings: {
      background_type: 'solid',
      background_value: '#000000',
      background_value_2: '#000000',
      text_color: '#22c55e',
      accent_color: '#22c55e',
      font_family: 'JetBrains Mono',
      button_style: 'outline',
      show_avatar: true,
      show_social_icons: true,
      avatar_size: 'medium',
      layout: 'centered',
      neon_glow: true,
    },
  },
} as const;

export type BioTemplateId = keyof typeof BIO_TEMPLATES;

export const FONT_OPTIONS = [
  { id: 'Inter', name: 'Inter', family: 'Inter, sans-serif', google: 'Inter' },
  { id: 'Playfair Display', name: 'Playfair Display', family: '"Playfair Display", serif', google: 'Playfair+Display' },
  { id: 'Space Grotesk', name: 'Space Grotesk', family: '"Space Grotesk", sans-serif', google: 'Space+Grotesk' },
  { id: 'DM Sans', name: 'DM Sans', family: '"DM Sans", sans-serif', google: 'DM+Sans' },
  { id: 'Bebas Neue', name: 'Bebas Neue', family: '"Bebas Neue", sans-serif', google: 'Bebas+Neue' },
  { id: 'JetBrains Mono', name: 'JetBrains Mono', family: '"JetBrains Mono", monospace', google: 'JetBrains+Mono' },
] as const;

export const BLOCK_TYPES = [
  { id: 'link', name: 'Link', icon: 'Link' },
  { id: 'youtube', name: 'YouTube', icon: 'Youtube' },
  { id: 'spotify', name: 'Spotify', icon: 'Music' },
  { id: 'text', name: 'Text', icon: 'Type' },
  { id: 'image', name: 'Image', icon: 'Image' },
  { id: 'contact_form', name: 'Contact Form', icon: 'Mail' },
] as const;
