// Bio page theme presets
export const THEME_PRESETS = {
  minimal_white: {
    id: 'minimal_white',
    name: 'Minimal White',
    theme: 'minimal',
    page_settings: {
      background_type: 'solid',
      background_value: '#ffffff',
      background_value_2: '#ffffff',
      text_color: '#111827',
      accent_color: '#3361FF',
      font_family: 'Inter',
      button_style: 'rounded',
      show_avatar: true,
      show_social_icons: true,
    },
  },
  dark_mode: {
    id: 'dark_mode',
    name: 'Dark Mode',
    theme: 'dark',
    page_settings: {
      background_type: 'solid',
      background_value: '#111827',
      background_value_2: '#111827',
      text_color: '#f9fafb',
      accent_color: '#60a5fa',
      font_family: 'Inter',
      button_style: 'rounded',
      show_avatar: true,
      show_social_icons: true,
    },
  },
  gradient_blue: {
    id: 'gradient_blue',
    name: 'Gradient Blue',
    theme: 'gradient',
    page_settings: {
      background_type: 'gradient',
      background_value: '#3b82f6',
      background_value_2: '#1d4ed8',
      text_color: '#ffffff',
      accent_color: '#ffffff',
      font_family: 'Inter',
      button_style: 'pill',
      show_avatar: true,
      show_social_icons: true,
    },
  },
  sunset_orange: {
    id: 'sunset_orange',
    name: 'Sunset Orange',
    theme: 'gradient',
    page_settings: {
      background_type: 'gradient',
      background_value: '#f97316',
      background_value_2: '#ea580c',
      text_color: '#ffffff',
      accent_color: '#ffffff',
      font_family: 'Georgia',
      button_style: 'pill',
      show_avatar: true,
      show_social_icons: true,
    },
  },
  forest_green: {
    id: 'forest_green',
    name: 'Forest Green',
    theme: 'gradient',
    page_settings: {
      background_type: 'gradient',
      background_value: '#059669',
      background_value_2: '#047857',
      text_color: '#ffffff',
      accent_color: '#a7f3d0',
      font_family: 'Georgia',
      button_style: 'rounded',
      show_avatar: true,
      show_social_icons: true,
    },
  },
  neon_purple: {
    id: 'neon_purple',
    name: 'Neon Purple',
    theme: 'gradient',
    page_settings: {
      background_type: 'gradient',
      background_value: '#a855f7',
      background_value_2: '#7c3aed',
      text_color: '#ffffff',
      accent_color: '#e9d5ff',
      font_family: 'Inter',
      button_style: 'outline',
      show_avatar: true,
      show_social_icons: true,
    },
  },
} as const;

export type ThemePresetId = keyof typeof THEME_PRESETS;

export const SOCIAL_PLATFORMS = [
  { id: 'instagram', name: 'Instagram', icon: 'Instagram', urlPrefix: 'https://instagram.com/' },
  { id: 'youtube', name: 'YouTube', icon: 'Youtube', urlPrefix: 'https://youtube.com/' },
  { id: 'tiktok', name: 'TikTok', icon: 'Music2', urlPrefix: 'https://tiktok.com/@' },
  { id: 'twitter', name: 'Twitter/X', icon: 'Twitter', urlPrefix: 'https://x.com/' },
  { id: 'linkedin', name: 'LinkedIn', icon: 'Linkedin', urlPrefix: 'https://linkedin.com/in/' },
  { id: 'facebook', name: 'Facebook', icon: 'Facebook', urlPrefix: 'https://facebook.com/' },
  { id: 'twitch', name: 'Twitch', icon: 'Twitch', urlPrefix: 'https://twitch.tv/' },
  { id: 'discord', name: 'Discord', icon: 'MessageCircle', urlPrefix: 'https://discord.gg/' },
  { id: 'spotify', name: 'Spotify', icon: 'Music', urlPrefix: 'https://open.spotify.com/user/' },
  { id: 'apple_music', name: 'Apple Music', icon: 'Music', urlPrefix: 'https://music.apple.com/' },
  { id: 'website', name: 'Website', icon: 'Globe', urlPrefix: 'https://' },
] as const;
